---
title: "K comparison"
author: "Renata Diaz"
date: "8/23/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(MATSS)
library(matssldats)
library(LDATS)
library(drake)
library(dplyr)
library(ggplot2)
# define where the cache is located
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("drake", "drake-cache.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)

loadd(model_summary, cache = cache)
```

## Predicted absolute abundances: Portal, 3, 6, 9, 12 topics

```{r load best models for Portal}

portal_model_summary <- model_summary %>%
    filter(data_object_name == "portal_ann_data", 
           changepoints == 0,
           formula == "gamma ~ year",
           k %in% c(3, 6, 9, 12)) %>%
    group_by(k) %>%
    filter(meanAICc == min(meanAICc)) %>%
    ungroup() %>%
    distinct()

portal_predictions <- list() 

for(i in 1:nrow(portal_model_summary)) {
    portal_predictions[[i]] <- ts_predict(as.list(portal_model_summary[i, ]), seed = 1977)$prediction %>%
        mutate(k = portal_model_summary$k[i])
}

all_pred <- bind_rows(portal_predictions)

all_pred[ which(all_pred$source == "observed"), "k"] <- NA


print(portal_model_summary)

```

```{r plot absolute abund predictions, fig.dim = c(15, 15)} 
abs_abund_plot <- ggplot(data = filter(all_pred, source == "observed"), aes(x = timestep, y = abundance)) +
    geom_line() +
    geom_line(data = filter(all_pred, source == "pred", k %in% c(3, 12)), aes(x = timestep, y = abundance, color = as.factor(k))) +
    theme_bw() +
    facet_wrap(species ~ .)

abs_abund_plot
```

```{r plot relative abundances, fig.dim = c(15, 15)}
rel_pred <- all_pred %>%
    group_by(timestep, source, k) %>%
    mutate(abundance = abundance / sum(abundance)) %>%
    ungroup()

rel_abund_plot <- ggplot(data = filter(rel_pred, source == "observed"), aes(x = timestep, y = abundance)) +
    geom_line() +
    geom_line(data = filter(rel_pred, source == "pred", k %in% c(3, 12)), aes(x = timestep, y = abundance, color = as.factor(k))) +
    theme_bw() +
    facet_wrap(species ~ .)

rel_abund_plot
```