---
title: "Summary report"
author: "Renata Diaz"
date: "8/19/2019"
output: github_document
---

```{r setup, include=FALSE}

library(MATSS)
library(matssldats)
library(LDATS)
library(drake)
library(dplyr)
# define where the cache is located
db <- DBI::dbConnect(RSQLite::SQLite(), here::here("drake", "drake-cache.sqlite"))
cache <- storr::storr_dbi("datatable", "keystable", db)

loadd(model_summary, cache = cache)

```

## AICc: All models, all k, all seeds

```{r expand full like results, echo = F}

max_k <- length(unique(model_summary$k))
max_seed <- length(unique(model_summary$seed))
max_models <- length(unique(model_summary$ts_model_desc))
max_data <- length(unique(model_summary$data_object_name))


```

### Mean AICcs

```{r plot mean AICcs, fig.dim=c(min(max_k * 3, 12), length = max_data * 5), echo =F}

library(ggplot2)

make_mean_aic_plot <- function(model_data) {
    ggplot(data = model_data, aes(x = ts_model_desc, y = meanAICc, colour = ts_model_desc, fill = ts_model_desc)) + 
         geom_point(size= 1) +
        geom_violin(stat = "ydensity") +
        theme_bw() +
        facet_grid(cols = vars(as.factor(k))) +
        ggtitle(paste0("Mean AICc: ", label = model_data$data_object_name[1])) +
        theme(legend.position = "bottom") +
        theme(axis.text.x = element_text(angle = 60, hjust = 1))
}

AIC_mean_plots <- lapply(unique(model_summary$data_object_name),
                         FUN = function(dat_name) return(make_mean_aic_plot(dplyr::filter(model_summary, data_object_name == dat_name))))

gridExtra::grid.arrange(grobs = AIC_mean_plots, ncol = 1)
```

### Median AICcs

```{r plot median AICcs,  fig.dim=c(min(max_k * 3, 12), length = max_data * 5), echo =F}

make_median_aic_plot <- function(model_data) {
    ggplot(data = model_data, aes(x = ts_model_desc, y = medianAICc, colour = ts_model_desc, fill = ts_model_desc)) + 
        geom_point(size= 1) +
        geom_violin(stat = "ydensity") +
        theme_bw() +
        facet_grid(cols = vars(as.factor(k))) +
        ggtitle(paste0("Median AICc: ", label = model_data$data_object_name[1])) +
        theme(legend.position = "bottom") +
        theme(axis.text.x = element_text(angle = 60, hjust = 1))
}

AIC_median_plots <- lapply(unique(model_summary$data_object_name),
                           FUN = function(dat_name) return(make_median_aic_plot(dplyr::filter(model_summary, data_object_name == dat_name))))

gridExtra::grid.arrange(grobs = AIC_median_plots, ncol = 1)

```


## Best AICcs for each dataset

```{r plot best AICc, fig.dim=c(min(max_k * 3, 12), length = max_data * 4), eval = T, echo = F} 

best_model_summary <- model_summary %>%
    group_by(data_object_name) %>%
    arrange(meanAICc) %>%
    mutate(meanAICc_rank = row_number()) %>%
    ungroup() %>%
    filter(meanAICc_rank <= 10)


make_best_mean_aicc_plot <- function(model_data) {
    ggplot(data = model_data, aes(x = ts_model_desc, y = meanAICc, colour = ts_model_desc)) + 
        geom_jitter(width = 0.05, height =0) +
        facet_grid(cols = vars(as.factor(k))) +
        theme_bw() +
        ggtitle(label = paste0(model_data$data_object_name[1], " mean")) +
        theme(legend.position = "bottom") +
        theme(axis.text.x = element_text(angle = 60, hjust = 1))
}


best_mean_AIC_plots <- lapply(unique(best_model_summary$data_object_name),
                              FUN = function(dat_name) return(make_best_mean_aicc_plot(dplyr::filter(best_model_summary, data_object_name == dat_name))))

gridExtra::grid.arrange(grobs = best_mean_AIC_plots, ncol = 1)


```


## Predicted abundances for all species

### Best TS + LDA model

```{r plot best observed v predicted, eval  =T, echo = F, fig.dim=c(12,10)}

best_ts_models <- filter(best_model_summary, meanAICc_rank == 1)

best_ts_models <- lapply(as.list(1:nrow(best_ts_models)),
                         FUN = function(rowindex) return(as.list(best_ts_models[rowindex,])))

best_predictions <- lapply(best_ts_models, FUN = ts_predict, lda_model = NULL, ts_model = NULL, data = NULL, sim = NULL, seed = 1977)

plot_obs_pred <- function(prediction_list) {
    obs_pred_data = prediction_list$prediction
    
    if(length(unique(obs_pred_data$species)) > 25) {
        
        speciesTotals <- obs_pred_data %>%
            group_by(species, source) %>%
            summarize(total_n = sum(abundance)) %>%
            ungroup() %>%
            group_by(species) %>%
            summarize(max_total_n = max(total_n)) %>%
            ungroup()
        
        cutoff = sort(speciesTotals$max_total_n, decreasing = T)[25]
        speciesTotals <- filter(speciesTotals, max_total_n >= cutoff)
    
        obs_pred_data <- obs_pred_data %>%
            filter(species %in% speciesTotals$species)
        
    }
    
    obs_pred_plot <- ggplot2::ggplot(data = obs_pred_data, aes(x = timestep, y = abundance, color = source)) +
        ggplot2::geom_line() +
        ggplot2::theme_bw() +
        ggplot2::facet_wrap(facets = species ~ .) +
        ggplot2::ggtitle(prediction_list$model_name)
    
    return(obs_pred_plot)
}


all_plots <- lapply(best_predictions, FUN = plot_obs_pred)

for(i in 1:length(all_plots)) {
    gridExtra::grid.arrange(grobs = all_plots[i], ncol = 1)
}

```

## LDA + TS plots for best predictions

```{r load da and ts for plots}

loadd(c(best_ts_models[[1]]$ts_object_name,
        best_ts_models[[1]]$lda_object_name,
        best_ts_models[[2]]$ts_object_name,
        best_ts_models[[2]]$lda_object_name), character_only = T, cache = cache)

```

### Portal - 12 topics, 0; gamma ~ year

```{r plot portal best, echo = F}
plot(lda_portal_ann_data_12$lda[[best_ts_models[[1]]$lda_model_index]])
plot(ts_lda_portal_ann_data_12$ts[[best_ts_models[[1]]$ts_model_index]])
```

### BBS - 3 topics, 0; gamma ~ year
```{r plot bbs best, echo = F}
plot(lda_bbs_data_rtrg_2_11_3$lda[[best_ts_models[[2]]$lda_model_index]])
plot(ts_lda_bbs_data_rtrg_2_11_3$ts[[best_ts_models[[2]]$ts_model_index]])
```


## Assorted other plots

### Portal with 6 topics
```{r get portal best with 6, echo = F}

portal_6 <- best_model_summary %>%
    dplyr::filter(data_object_name == "portal_ann_data", k == 6) %>%
    dplyr::filter(meanAICc == min(meanAICc))
    
loadd(portal_6$ts_object_name[1], portal_6$lda_object_name, character_only = T, cache = cache)

portal_6_pred <- ts_predict(as.list(portal_6[1,]), lda_model = NULL, ts_model = NULL, data = NULL, sim = NULL, seed = 1977)

portal_6_pred_plot <- plot_obs_pred(portal_6_pred)

portal_6_pred_plot

plot(lda_portal_ann_data_6$lda[[portal_6$lda_model_index[1]]])
plot(ts_lda_portal_ann_data_6$ts[[portal_6$ts_model_index[1]]])

```