language: r
cache:
- packages
sudo: required
dist: bionic
warnings_are_errors: false

addons:
  apt:
    packages:
      - libgsl0-dbg
      - libgsl0-dev
      - "python3.6"
      - "python3-pip"
    update: true

before_install:
  - sudo pip3 install --upgrade setuptools
  - sudo pip3 install --upgrade git+https://git@github.com/weecology/retriever.git
  - python3 -c 'import retriever;retriever.check_for_updates()'
  
matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - R CMD INSTALL .
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'covr::codecov()'
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_PAT
      keep-history: true
      local-dir: docs
      on:
        branch: master
