language: r
cache:
- packages
sudo: required
dist: "xenial"
warnings_are_errors: false

r_packages:
  - covr

addons:
  apt:
    packages:
      - libgsl0-dbg
      - libgsl0-dev
    update: true

before_install:
  - wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  # Useful for debugging any issues with conda
  - conda info -a
  - conda create -q -n test-environment python=3
  - source activate test-environment
  - conda install -c conda-forge retriever
  - retriever
  - python -c 'import retriever;retriever.check_for_updates()'

matrix:
  include:
  - r: devel
  - r: release
    after_success:
    - R CMD INSTALL .
    - rm README.Rmd
    - Rscript -e 'pkgdown::build_site()'
    - Rscript -e 'covr::codecov()'
    deploy:
      provider: pages
      skip-cleanup: true
      github-token: $GITHUB_PAT
      keep-history: true
      local-dir: docs
      on:
        branch: master
