coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project: yes
      default:
        target: auto
        threshold: 1%
    patch: yes
      default:
        target: auto
        threshold: 1%
    changes: yes
    

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment: true
  layout: "header, diff"
  behavior: default
  require_changes: no

codecov:
  notify:
    require_ci_to_pass: yes
